FROM alpine:latest
RUN apk add --update make

ARG ARCH
ENV ARCH ${ARCH}

COPY report_arch.sh report_arch.sh
RUN ./report_arch.sh

RUN ./report_arch.sh

COPY test/Makefile Makefile
COPY Makefile.inc Makefile.inc
RUN IMAGE_NAME=test make arg
