---
- name: Download Packer source
  ansible.builtin.git:
    repo: "{{ packer_source_url }}"
    dest: "{{ packer_destination }}"
- name: Build Packer project
  command: go build -o bin/packer .
  args:
    creates: bin/packer
    chdir: "{{ packer_destination }}"
- name: Symlink Packer binaries to /usr/local/bin
  file:
    state: link
    src: "{{ packer_destination }}/bin/packer"
    dest: "{{ packer_install_prefix }}/bin/packer"
