FROM ubuntu:22.04

COPY <<EOF /etc/apt/sources.list.d/s390x.list
deb [arch=s390x] http://ports.ubuntu.com/ jammy main restricted
deb [arch=s390x] http://ports.ubuntu.com/ jammy-updates main restricted
deb [arch=s390x] http://ports.ubuntu.com/ jammy universe
deb [arch=s390x] http://ports.ubuntu.com/ jammy-updates universe
deb [arch=s390x] http://ports.ubuntu.com/ jammy multiverse
deb [arch=s390x] http://ports.ubuntu.com/ jammy-updates multiverse
deb [arch=s390x] http://ports.ubuntu.com/ jammy-backports main restricted universe multiverse
EOF

COPY <<EOF /etc/apt/sources.list
deb [arch=amd64] http://us.archive.ubuntu.com/ubuntu jammy main restricted
deb [arch=amd64] http://us.archive.ubuntu.com/ubuntu jammy-updates main restricted
deb [arch=amd64] http://us.archive.ubuntu.com/ubuntu jammy universe
deb [arch=amd64] http://us.archive.ubuntu.com/ubuntu jammy-updates universe
deb [arch=amd64] http://us.archive.ubuntu.com/ubuntu jammy multiverse
deb [arch=amd64] http://us.archive.ubuntu.com/ubuntu jammy-updates multiverse
deb [arch=amd64] http://us.archive.ubuntu.com/ubuntu jammy-backports main restricted universe multiverse
EOF

RUN apt update && apt install -y binfmt-support qemu-user-static && dpkg --add-architecture s390x
RUN mkdir /output
COPY fetch-packages.sh /root/fetch-packages.sh
ENTRYPOINT ["/root/fetch-packages.sh"]
