name: Test Build ARG
on: push

jobs:
  build:
    name: test build arg
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        tags: |
          uk.icr.io/jt-cloud-api-adaptor/test-build-arg:latest
        push: false
        context: podvm
        platforms: linux/amd64
        file: |
          podvm/Dockerfile.arg_test
        build-args: |
          "CLOUD_PROVIDER=abc"
          "ARCH=s390x"
