---
name: matrix
on:
  push:

jobs:
  build:
    name: Create pod vm image
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        os:
          # Please keep this list in alphabetical order.
          - centos
          - ubuntu
        provider:
          # Please keep this list in alphabetical order.
          - aws
          - azure
          - ibmcloud
          - libvirt
          - vsphere
        include:
          - os: centos
            dockerfile: Dockerfile.podvm.centos
          - os: ubuntu
            dockerfile: Dockerfile.podvm
          - os: ubuntu
            provider: ibmcloud
            arch: s390x
          - os: ubuntu
            provider: ibmcloud
            arch: x86_64
        runner:
          - ubuntu-latest
    steps:
    - name: Check matrix
      run: echo ${{ matrix.provider }} ${{ matrix.os }}  ${{ matrix.arch }}  ${{ matrix.dockerfile }}
