---
name: matrix
on:
  push:

jobs:
  build:
    name: Create pod vm image
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        os:
          # Please keep this list in alphabetical order.
          - centos
          - ubuntu
        provider:
          # Please keep this list in alphabetical order.
          - aws
          - azure
          - ibmcloud
          - libvirt
          - vsphere
        target_arch:
          - amd64
        include:
          - os: centos
            dockerfile: Dockerfile.podvm.centos
          - os: ubuntu
            dockerfile: Dockerfile.podvm
          - provider: ibmcloud
            target_arch: s390x
        runner:
          - ubuntu-latest
    steps:
    - name: Check matrix
      run: echo ${{ matrix.provider }} ${{ matrix.os }} ${{ matrix.target_arch }} ${{ matrix.dockerfile }}
