---

name: Podvm

on:
  push:

jobs:
  packer:
    runs-on: ubuntu-latest
    name: generic-image-build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install qemu
        run: sudo apt-get install -y qemu qemu-kvm

      - name: Setup `packer` from renamed action
        uses: hashicorp/packer-github-actions@rewrite-to-typescript
        id: setup
        with:
          version: "1.8.1"

      - name: Run `packer` init
        run: packer init .
        working-directory: podvm

      - name: Build `podvm` image 
        run: packer build .
        working-directory: podvm

      - name: Publish Artifact
        uses: actions/upload-artifact@v3
        with:
          name: podvm-image-amd64.qcow2
          path: podvm/output/peer-pod.qcow2
