---

name: Podvm

on:
  push:

jobs:
  packer:
    runs-on: ubuntu-latest
    name: generic-image-build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # validate templates
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: podvm/qcow.pkr.hcl
        env:
          PACKER_LOG: 1

      # build artifact
      - name: Build Artifact
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort"
          target: podvm/qcow.pkr.hcl
        env:
          PACKER_LOG: 1

      - name: Publish Artifact
        uses: actions/upload-artifact@v3
        with:
          name: podvm-image-amd64.qcow2
          path: podvm/output/peer-pod.qcow2
