name: Create Pod VM Image
on:
  workflow_run:
    workflows: ["Create Pod VM Builder Image"]
    types: 
      - completed

jobs:
  build:
    name: Create pod vm image
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        os:
          # Please keep this list in alphabetical order.
          - ubuntu
        include:
          - os: ubuntu
            dockerfile: Dockerfile.podvm
        runner:
          - ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    #- name: Set up QEMU
    #  uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Quay container Registry
      uses: docker/login-action@v2
      with:
        registry: uk.icr.io
        username: ${{ secrets.IBM_IAM_USERNAME }}
        password: ${{ secrets.IBM_IAM_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        tags: |
          uk.icr.io/jt-cloud-api-adaptor/cloud-api-adaptor-podvm-${{ matrix.os }}:latest
        push: true
        context: podvm
        platforms: linux/amd64
        file: |
          podvm/${{ matrix.dockerfile }}
        build-args: |
          "BUILDER_IMG=uk.icr.io/jt-cloud-api-adaptor/cloud-api-adaptor-podvm-builder-ubuntu:latest"
